Repository VolkovLabs/business-links, pull requests merged in 2025-06, with the labels that each got.

#40 Add support for kiosk mode
  CHANGELOG.md
  docker-compose.yml
  package.json
  provisioning/dashboards/links.json
  src/components/LinksPanel/LinksPanel.tsx
  src/components/editors/GroupsEditor/components/GroupEditor/GroupEditor.tsx
  src/components/editors/GroupsEditor/components/GroupEditor/components/LinkEditor/LinkEditor.test.tsx
  src/components/editors/GroupsEditor/components/GroupEditor/components/LinkEditor/LinkEditor.tsx
  src/constants.ts
  src/hooks/index.ts
  src/hooks/useGrafanaLocationService.test.ts
  src/hooks/useGrafanaLocationService.ts
  src/migration.test.ts
  src/migration.ts
  src/plugin.json
  src/types/panel.ts
  src/utils/links.test.ts
  src/utils/links.ts
  src/utils/test.ts
Labels: bug

#42 Add hide tooltip option and recalc sticky on resize with dynamic menu font size
  CHANGELOG.md
  package-lock.json
  provisioning/dashboards/dynamic-font-size.json
  src/components/LinksPanel/components/LinkElement/LinkElement.test.tsx
  src/components/LinksPanel/components/LinkElement/LinkElement.tsx
  src/components/LinksPanel/components/MenuElement/MenuElement.test.tsx
  src/components/LinksPanel/components/MenuElement/MenuElement.tsx
  src/components/LinksPanel/components/TimePickerElement/TimePickerElement.test.tsx
  src/components/LinksPanel/components/TimePickerElement/TimePickerElement.tsx
  src/components/editors/GroupsEditor/components/GroupEditor/GroupEditor.tsx
  src/components/editors/GroupsEditor/components/GroupEditor/components/LinkEditor/LinkEditor.test.tsx
  src/components/editors/GroupsEditor/components/GroupEditor/components/LinkEditor/LinkEditor.tsx
  src/constants.ts
  src/hooks/useContentPosition.test.tsx
  src/hooks/useContentPosition.ts
  src/migration.test.ts
  src/migration.ts
  src/types/links.ts
  src/types/panel.ts
  src/utils/links.ts
  src/utils/test.ts
Labels: enhancement, enterprise

#44 Add custom padding and increase grid width
  src/components/LinksPanel/LinksPanel.tsx
  src/components/LinksPanel/components/LinksGridLayout/LinksGridLayout.styles.ts
  src/components/LinksPanel/components/LinksGridLayout/LinksGridLayout.test.tsx
  src/components/LinksPanel/components/LinksGridLayout/LinksGridLayout.tsx
  src/migration.test.ts
  src/migration.ts
  src/module.ts
  src/types/panel.ts
  src/utils/test.ts
Labels: enhancement

#45 Add LLM App link integration
  .config/jest.config.js
  .config/jest/utils.js
  CHANGELOG.md
  docker-compose.yml
  jest-setup.js
  package-lock.json
  package.json
  provisioning/dashboards/llm-app.json
  provisioning/plugins/app.yaml
  src/__mocks__/@grafana/ui.tsx
  src/components/LinksPanel/components/ChatDrawer/ChatDrawer.styles.ts
  src/components/LinksPanel/components/ChatDrawer/ChatDrawer.test.tsx
  src/components/LinksPanel/components/ChatDrawer/ChatDrawer.tsx
  src/components/LinksPanel/components/LinkElement/LinkElement.test.tsx
  src/components/LinksPanel/components/LinkElement/LinkElement.tsx
  src/components/LinksPanel/components/LinksGridLayout/LinksGridLayout.tsx
  src/components/LinksPanel/components/MenuElement/MenuElement.tsx
  src/components/editors/GroupsEditor/GroupsEditor.tsx
  src/components/editors/GroupsEditor/components/GroupEditor/components/LinkEditor/LinkEditor.test.tsx
  src/components/editors/GroupsEditor/components/GroupEditor/components/LinkEditor/LinkEditor.tsx
  src/constants.ts
  src/hooks/index.ts
  src/hooks/useDrawerLlmChat.test.tsx
  src/hooks/useDrawerLlmChat.ts
  src/migration.test.ts
  src/migration.ts
  src/types/links.ts
  src/types/panel.ts
  src/utils/links.test.ts
  src/utils/links.ts
  test/panel.spec.ts
  test/utils/links.ts
Labels: enhancement, enterprise
